version: "3"
services:
    deloitte_backend:
        container_name: deloitte_backend
        build:
            context: .
            dockerfile: Dockerfile
        image: deloitte_backend
        environment:
            - DJANGO_SECRET_KEY=some_secret_key
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin
            - DJANGO_DB_NAME=gpapp
            - DJANGO_DB_USER=sa
            - DJANGO_DB_PASS=h4Gl*IdRO+
            - DJANGO_DB_HOST=deloitte_db
            - DJANGO_DB_PORT=1433
        networks:
            - deloitte_network
        ports:
            - 8000:8000
        restart: always
        depends_on:
            deloitte_db:
                condition: service_healthy
        entrypoint: ./entrypoint.sh

    deloitte_db:
        container_name: deloitte_db
        build:
            context: .
            dockerfile: Dockerfile.db
        image: deloitte_db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_DB_NAME=gpapp
            - MSSQL_SA_PASSWORD=h4Gl*IdRO+
            - MSSQL_PID=Developer
        networks:
            - deloitte_network
        ports:
            - 1433:1433
        restart: always
        healthcheck:
            test: "/opt/mssql-tools/bin/sqlcmd -h -1 -t 1 -U sa -P h4Gl*IdRO+ -Q 'SET NOCOUNT ON; Select SUM(state) from sys.databases'"
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - db_volume:/var/opt/mssql

networks:
    deloitte_network:

volumes:
    db_volume:
